security:
  oauth2:
    client:
      registration:
        facebook:
          clientId: 782822670383867
          client-secret: c394fdc67d480d433c66d5d462803e37
          scope:
            - email
            - public_profile